/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    //HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    //TopTools: typeof import('./src/components/TopTools.vue')['default']
  }
}
